name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Build
       uses: actions/setup-node@master
       with:
        node-version: '20.x'
     - run: yarn
     - run: yarn run build

     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         branch:	gh-pages
         publish_dir: ./dist
         github_token: ${{ secrets.CI_TEST }}
         user_name:	${{ secrets.USER_NAME }}
         user_email:	${{secrets.USER_EMAIL}}
         commit_message: 自动部署